"""FT-023: monthly wash-beta CF ledger (tune + holdout)."""

from __future__ import annotations

import argparse
import datetime as dt
from collections import defaultdict
from pathlib import Path

from config import load_config
from core.runtime_config import TradingAppRuntimeConfig, _to_engine_settings
from integrations.strategy_bootstrap import load_gudt_probe_rows, wash_beta_params_from_config
from reporting.gudt_wash_probe import load_probe_contexts
from strategy_gudt_route_a.wash_beta import simulate_wash_beta_day

TUNE_FROM = "2025-05-01"
TUNE_TO = "2025-12-31"
HOLD_FROM = "2026-01-01"
HOLD_TO = "2026-06-30"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[4]


def _monthly_table(picks: list[dict], start: str, end: str) -> tuple[str, dict]:
    sub = [p for p in picks if start <= p["day"] <= end]
    by_m: dict[str, list[float]] = defaultdict(list)
    for p in sub:
        by_m[p["day"][:7]].append(float(p["net"]))
    lines = ["| Month | n | net | wr% |", "|-------|---|-----|-----|"]
    total_n = 0
    total_net = 0.0
    for month in sorted(by_m):
        nets = by_m[month]
        wins = sum(1 for n in nets if n > 0)
        net = round(sum(nets), 2)
        wr = round(100.0 * wins / len(nets), 1) if nets else 0.0
        lines.append(f"| {month} | {len(nets)} | {net:+.2f} | {wr} |")
        total_n += len(nets)
        total_net += net
    lines.append(f"| **Total** | **{total_n}** | **{total_net:+.2f}** | |")
    stats = {"n": total_n, "net": round(total_net, 2)}
    return "\n".join(lines), stats


def main(argv: list[str] | None = None) -> int:
    root = _repo_root()
    ws = root / "workspaces" / "gudt-wash-beta-baseline"
    parser = argparse.ArgumentParser(description="FT-023 wash-beta CF ledger")
    parser.add_argument("--config", type=Path, default=ws / "config" / "config.yaml")
    parser.add_argument("--code", default="TMFR1")
    parser.add_argument("--cache-dir", type=Path, default=root / "tick_cache")
    parser.add_argument("--from-csv", type=Path, default=None)
    parser.add_argument(
        "--out",
        type=Path,
        default=root / "workspaces" / "gudt-baseline" / "WASH_BETA_LEDGER.md",
    )
    args = parser.parse_args(argv)

    cfg = TradingAppRuntimeConfig(_to_engine_settings(load_config(args.config)))
    wb = wash_beta_params_from_config(cfg)
    rows = load_gudt_probe_rows(
        cfg,
        code=args.code,
        cache_dir=args.cache_dir,
        from_date=TUNE_FROM,
        to_date=HOLD_TO,
        probe_csv_override=args.from_csv,
    )
    day_strs = sorted({r["day"] for r in rows})
    ctx_by_day = load_probe_contexts(args.code, day_strs, cache_dir=args.cache_dir)
    picks = []
    for day in sorted(ctx_by_day):
        sim = simulate_wash_beta_day(ctx_by_day[day], params=wb)
        if sim:
            picks.append({"day": day, "path": "wash_beta", **sim})

    tune_table, tune_stats = _monthly_table(picks, TUNE_FROM, TUNE_TO)
    hold_table, hold_stats = _monthly_table(picks, HOLD_FROM, HOLD_TO)

    md = f"""# Wash-beta CF ledger (open→flatten)

Generated by `ft023_wash_beta_ledger.py`. Oracle wash gate (probe CSV). Friction={wb.friction_points}pt.
Flatten={wb.force_flatten_time.strftime('%H:%M')}.

## Tune ({TUNE_FROM} .. {TUNE_TO})

{tune_table}

## Holdout ({HOLD_FROM} .. {HOLD_TO})

{hold_table}

---
*Updated {dt.date.today().isoformat()}*
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(md, encoding="utf-8")
    print(f"Wrote {args.out}")
    print(f"tune: n={tune_stats['n']} net={tune_stats['net']:+.2f}")
    print(f"holdout: n={hold_stats['n']} net={hold_stats['net']:+.2f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
