"""Summarize Alpha train counterfactual JSON — net_total / gate_summary (Playbook v1.7)."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parent.parent
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from reporting.gate_summary import (  # noqa: E402
    build_gate_summary,
    format_gate_report_table,
    format_warnings_block,
)

REPO = Path(__file__).resolve().parents[4]

TRAIN_PATTERNS = (
    "*train*.json",
    "*fingerprint*.json",
    "counterfactual_v2.1_train2025.json",
    "counterfactual_scb_train.json",
    "counterfactual_gdc_train.json",
    "counterfactual_gudt_train.json",
    "counterfactual_rvsf_train.json",
)


def _workspace_dirs(all_workspaces: bool, workspace: str | None) -> list[Path]:
    ws_root = REPO / "workspaces"
    if workspace:
        return [ws_root / workspace]
    if all_workspaces:
        return sorted(p for p in ws_root.glob("*-baseline") if p.is_dir())
    return []


def _find_train_jsons(ws_dir: Path) -> list[Path]:
    reports = ws_dir / "reports"
    if not reports.is_dir():
        return []
    found: list[Path] = []
    seen: set[str] = set()
    for pat in TRAIN_PATTERNS:
        for p in reports.glob(pat):
            if p.name in seen:
                continue
            seen.add(p.name)
            found.append(p)
    return sorted(found)


def _is_2025_train(payload: dict, *, split_2025: bool) -> bool:
    if not split_2025:
        return True
    fd = str(payload.get("from_date") or "")
    td = str(payload.get("to_date") or "")
    return fd.startswith("2025") or (fd <= "2025-12-31" and td >= "2025-01-01")


def summarize_file(path: Path, *, split_2025: bool) -> dict | None:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None
    if not _is_2025_train(payload, split_2025=split_2025):
        return None
    summary = build_gate_summary(payload)
    champ = summary.get("champion") or {}
    return {
        "file": str(path.relative_to(REPO)),
        "thesis": payload.get("thesis"),
        "from_date": payload.get("from_date"),
        "to_date": payload.get("to_date"),
        "outcome_hint": payload.get("outcome_hint"),
        "outcome_class": summary.get("outcome_class"),
        "warnings": summary.get("warnings"),
        "phase0_pass": (payload.get("phase0_gate") or {}).get("pass") is True,
        "champion": champ,
        "gate_summary": summary,
    }


def _print_table(rows: list[dict]) -> None:
    print(f"{'workspace':<28} {'net_total':>10} {'n':>5} {'net_mean':>9} {'outcome_class':<22} file")
    print("-" * 100)
    for row in rows:
        champ = row.get("champion") or {}
        ws = row["file"].split("/")[1] if "/" in row["file"] else "?"
        nt = champ.get("net_total")
        nt_s = f"{nt:.1f}" if isinstance(nt, (int, float)) else "—"
        nm = champ.get("net_mean")
        nm_s = f"{nm:.2f}" if isinstance(nm, (int, float)) else "—"
        oc = row.get("outcome_class") or "—"
        fname = Path(row["file"]).name[:36]
        print(f"{ws:<28} {nt_s:>10} {champ.get('n', '—'):>5} {nm_s:>9} {oc:<22} {fname}")


def _write_gate_snippet(ws_dir: Path, row: dict) -> None:
    gate_path = ws_dir / "gate_report.md"
    if not gate_path.is_file():
        return
    champ = row.get("champion")
    warnings = row.get("warnings") or []
    snippet = format_gate_report_table(champ)
    snippet += format_warnings_block(warnings)
    snippet += f"\n> Auto-generated by `summarize_alpha_train` · source: `{row['file']}`\n\n---\n\n"
    existing = gate_path.read_text(encoding="utf-8")
    marker = "<!-- gate-summary:auto -->"
    end_marker = "<!-- /gate-summary:auto -->"
    if marker in existing:
        before = existing.split(marker)[0]
        after = existing.split(end_marker)[-1] if end_marker in existing else ""
        new_body = f"{before}{marker}\n{snippet}{end_marker}{after}"
    else:
        new_body = f"{marker}\n{snippet}{end_marker}\n\n{existing}"
    gate_path.write_text(new_body, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Summarize Alpha train counterfactual JSON")
    parser.add_argument("--workspace", help="e.g. gudt-baseline")
    parser.add_argument("--all-workspaces", action="store_true")
    parser.add_argument("--split", dest="split_2025", action="store_true", help="Only 2025 train window")
    parser.add_argument("--write-gate-snippet", action="store_true")
    parser.add_argument("--json-out", help="Write combined JSON summary path")
    args = parser.parse_args(argv)

    dirs = _workspace_dirs(args.all_workspaces, args.workspace)
    if not dirs:
        parser.error("Specify --workspace NAME or --all-workspaces")

    all_rows: list[dict] = []
    for ws_dir in dirs:
        ws_rows: list[dict] = []
        for jpath in _find_train_jsons(ws_dir):
            row = summarize_file(jpath, split_2025=args.split_2025)
            if row:
                all_rows.append(row)
                ws_rows.append(row)
        if args.write_gate_snippet and ws_rows:
            best = max(
                ws_rows,
                key=lambda r: (
                    1 if "train" in Path(r["file"]).name else 0,
                    (r.get("champion") or {}).get("net_total") or -9999,
                ),
            )
            _write_gate_snippet(ws_dir, best)

    _print_table(all_rows)

    if args.json_out:
        out = Path(args.json_out)
        out.write_text(json.dumps(all_rows, ensure_ascii=False, indent=2), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
